## First use case
# FROM nginx:latest
# ADD . /usr/share/nginx/html/


## Second use case with alpine tag
# FROM nginx:alpine
# ADD . /usr/share/nginx/html/

## Third use case with version in alpine
FROM nginx:1.23.1-alpine
ADD . /usr/share/nginx/html/